---
- name: Déploiement Kubernetes
  hosts: workers
  become: true
  roles:
    - role: kubernetes
      kubernetes_role: "worker"
      kubernetes_apiserver_advertise_address: "{{ hostvars[groups['masters'][0]]['ansible_host'] }}"
      k8s_version: "1.35.8"
      installation_method: "{{ installation_method | default('vagrant') }}"
      kubernetes_join_command: "{{ kubernetes_join_command | default(omit) }}"
  tasks:
    - debug:
        var: kubernetes_role
